name: one_fits_all
task_name: classification

# LLM
trainable_llm_params: 
  - norm
lora_config: 
  - none

# Patch Embedding
patch_length: 16
patch_stride: 8
patch_embedding_dropout: 0.1

# Classification head
num_cnn_blocks: 3
cnn_channels: 128
kernel_size: 3
mlp_hidden: 1024
pooling_type: avg
use_batch_norm: True

# Classification head
dropout: 0
activation: relu




