# configs/main_config.yaml
defaults:
  - _self_
  - data_preparation: uea
  - model: deep_range
  - llm: Llama-3.2-1B 
  - training: training

run_flags:
  data_preparation: false
  run_training: false






